version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: verystrongpassword
      MONOG_INITDB_DATABASE: pet
    ports:
      - "27017:27017"
