spring:
  application:
    name: pet
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: pet
      username: root
      password: verystrongpassword

logging:
  level:
    org.springframework.http: TRACE
